[package]
name = "connector-core"
version.workspace = true
edition.workspace = true

[dependencies]
common = { workspace = true }
model = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
