[package]
name = "orderbook"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_decimal = { workspace = true }
ordered-float = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
rust_decimal_macros = { workspace = true }
